/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsExportsRouteImport } from './routes/settings.exports'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsAutoDistributionRouteImport } from './routes/settings.auto-distribution'
import { Route as ProfilesPointsUserIdRouteImport } from './routes/profiles.$pointsUserId'
import { Route as PointsTransfersRouteImport } from './routes/points.transfers'
import { Route as PointsExchangesRouteImport } from './routes/points.exchanges'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AdminSubstitutionsRouteImport } from './routes/admin.substitutions'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminPointPackagesRouteImport } from './routes/admin.point-packages'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminFixesRouteImport } from './routes/admin.fixes'
import { Route as AdminExchangeRatesRouteImport } from './routes/admin.exchange-rates'
import { Route as AdminEvaluationCriteriaRouteImport } from './routes/admin.evaluation-criteria'
import { Route as AccountReopenRouteImport } from './routes/account.reopen'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExportsRoute = SettingsExportsRouteImport.update({
  id: '/settings/exports',
  path: '/settings/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAutoDistributionRoute =
  SettingsAutoDistributionRouteImport.update({
    id: '/settings/auto-distribution',
    path: '/settings/auto-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilesPointsUserIdRoute = ProfilesPointsUserIdRouteImport.update({
  id: '/profiles/$pointsUserId',
  path: '/profiles/$pointsUserId',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsTransfersRoute = PointsTransfersRouteImport.update({
  id: '/points/transfers',
  path: '/points/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsExchangesRoute = PointsExchangesRouteImport.update({
  id: '/points/exchanges',
  path: '/points/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubstitutionsRoute = AdminSubstitutionsRouteImport.update({
  id: '/admin/substitutions',
  path: '/admin/substitutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/admin/reconciliation',
  path: '/admin/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPointPackagesRoute = AdminPointPackagesRouteImport.update({
  id: '/admin/point-packages',
  path: '/admin/point-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFixesRoute = AdminFixesRouteImport.update({
  id: '/admin/fixes',
  path: '/admin/fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExchangeRatesRoute = AdminExchangeRatesRouteImport.update({
  id: '/admin/exchange-rates',
  path: '/admin/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationCriteriaRoute = AdminEvaluationCriteriaRouteImport.update({
  id: '/admin/evaluation-criteria',
  path: '/admin/evaluation-criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReopenRoute = AccountReopenRouteImport.update({
  id: '/account/reopen',
  path: '/account/reopen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account/reopen': typeof AccountReopenRoute
  '/admin/evaluation-criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/exchange-rates': typeof AdminExchangeRatesRoute
  '/admin/fixes': typeof AdminFixesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/point-packages': typeof AdminPointPackagesRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/points/exchanges': typeof PointsExchangesRoute
  '/points/transfers': typeof PointsTransfersRoute
  '/profiles/$pointsUserId': typeof ProfilesPointsUserIdRoute
  '/settings/auto-distribution': typeof SettingsAutoDistributionRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account/reopen': typeof AccountReopenRoute
  '/admin/evaluation-criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/exchange-rates': typeof AdminExchangeRatesRoute
  '/admin/fixes': typeof AdminFixesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/point-packages': typeof AdminPointPackagesRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/points/exchanges': typeof PointsExchangesRoute
  '/points/transfers': typeof PointsTransfersRoute
  '/profiles/$pointsUserId': typeof ProfilesPointsUserIdRoute
  '/settings/auto-distribution': typeof SettingsAutoDistributionRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account/reopen': typeof AccountReopenRoute
  '/admin/evaluation-criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/exchange-rates': typeof AdminExchangeRatesRoute
  '/admin/fixes': typeof AdminFixesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/point-packages': typeof AdminPointPackagesRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/points/exchanges': typeof PointsExchangesRoute
  '/points/transfers': typeof PointsTransfersRoute
  '/profiles/$pointsUserId': typeof ProfilesPointsUserIdRoute
  '/settings/auto-distribution': typeof SettingsAutoDistributionRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/help'
    | '/login'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/account/reopen'
    | '/admin/evaluation-criteria'
    | '/admin/exchange-rates'
    | '/admin/fixes'
    | '/admin/members'
    | '/admin/point-packages'
    | '/admin/reconciliation'
    | '/admin/substitutions'
    | '/oauth/consent'
    | '/points/exchanges'
    | '/points/transfers'
    | '/profiles/$pointsUserId'
    | '/settings/auto-distribution'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/help'
    | '/login'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/account/reopen'
    | '/admin/evaluation-criteria'
    | '/admin/exchange-rates'
    | '/admin/fixes'
    | '/admin/members'
    | '/admin/point-packages'
    | '/admin/reconciliation'
    | '/admin/substitutions'
    | '/oauth/consent'
    | '/points/exchanges'
    | '/points/transfers'
    | '/profiles/$pointsUserId'
    | '/settings/auto-distribution'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/help'
    | '/login'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/account/reopen'
    | '/admin/evaluation-criteria'
    | '/admin/exchange-rates'
    | '/admin/fixes'
    | '/admin/members'
    | '/admin/point-packages'
    | '/admin/reconciliation'
    | '/admin/substitutions'
    | '/oauth/consent'
    | '/points/exchanges'
    | '/points/transfers'
    | '/profiles/$pointsUserId'
    | '/settings/auto-distribution'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AccountReopenRoute: typeof AccountReopenRoute
  AdminEvaluationCriteriaRoute: typeof AdminEvaluationCriteriaRoute
  AdminExchangeRatesRoute: typeof AdminExchangeRatesRoute
  AdminFixesRoute: typeof AdminFixesRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPointPackagesRoute: typeof AdminPointPackagesRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminSubstitutionsRoute: typeof AdminSubstitutionsRoute
  OauthConsentRoute: typeof OauthConsentRoute
  PointsExchangesRoute: typeof PointsExchangesRoute
  PointsTransfersRoute: typeof PointsTransfersRoute
  ProfilesPointsUserIdRoute: typeof ProfilesPointsUserIdRoute
  SettingsAutoDistributionRoute: typeof SettingsAutoDistributionRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsExportsRoute: typeof SettingsExportsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/exports': {
      id: '/settings/exports'
      path: '/settings/exports'
      fullPath: '/settings/exports'
      preLoaderRoute: typeof SettingsExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/auto-distribution': {
      id: '/settings/auto-distribution'
      path: '/settings/auto-distribution'
      fullPath: '/settings/auto-distribution'
      preLoaderRoute: typeof SettingsAutoDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$pointsUserId': {
      id: '/profiles/$pointsUserId'
      path: '/profiles/$pointsUserId'
      fullPath: '/profiles/$pointsUserId'
      preLoaderRoute: typeof ProfilesPointsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/transfers': {
      id: '/points/transfers'
      path: '/points/transfers'
      fullPath: '/points/transfers'
      preLoaderRoute: typeof PointsTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/exchanges': {
      id: '/points/exchanges'
      path: '/points/exchanges'
      fullPath: '/points/exchanges'
      preLoaderRoute: typeof PointsExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/substitutions': {
      id: '/admin/substitutions'
      path: '/admin/substitutions'
      fullPath: '/admin/substitutions'
      preLoaderRoute: typeof AdminSubstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/point-packages': {
      id: '/admin/point-packages'
      path: '/admin/point-packages'
      fullPath: '/admin/point-packages'
      preLoaderRoute: typeof AdminPointPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fixes': {
      id: '/admin/fixes'
      path: '/admin/fixes'
      fullPath: '/admin/fixes'
      preLoaderRoute: typeof AdminFixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exchange-rates': {
      id: '/admin/exchange-rates'
      path: '/admin/exchange-rates'
      fullPath: '/admin/exchange-rates'
      preLoaderRoute: typeof AdminExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation-criteria': {
      id: '/admin/evaluation-criteria'
      path: '/admin/evaluation-criteria'
      fullPath: '/admin/evaluation-criteria'
      preLoaderRoute: typeof AdminEvaluationCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reopen': {
      id: '/account/reopen'
      path: '/account/reopen'
      fullPath: '/account/reopen'
      preLoaderRoute: typeof AccountReopenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AccountReopenRoute: AccountReopenRoute,
  AdminEvaluationCriteriaRoute: AdminEvaluationCriteriaRoute,
  AdminExchangeRatesRoute: AdminExchangeRatesRoute,
  AdminFixesRoute: AdminFixesRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPointPackagesRoute: AdminPointPackagesRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminSubstitutionsRoute: AdminSubstitutionsRoute,
  OauthConsentRoute: OauthConsentRoute,
  PointsExchangesRoute: PointsExchangesRoute,
  PointsTransfersRoute: PointsTransfersRoute,
  ProfilesPointsUserIdRoute: ProfilesPointsUserIdRoute,
  SettingsAutoDistributionRoute: SettingsAutoDistributionRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsExportsRoute: SettingsExportsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
