#!/usr/bin/env sh
set -e

[ "$HUSKY" = "0" ] && exit 0

commit_msg_file=$1
case "$commit_msg_file" in
  "" | /*) ;;
  *) commit_msg_file="$(pwd)/$commit_msg_file" ;;
esac

if [ -n "$commit_msg_file" ]; then
  shift
  (cd web-app && ./.husky/prepare-commit-msg "$commit_msg_file" "$@")
else
  (cd web-app && ./.husky/prepare-commit-msg)
fi
