#!/usr/bin/env sh

# Commitizenでコミットメッセージを作成し、エディタが開かないようにする
if [ -z "$2" ] || [ "$2" = "message" ]; then
  # 標準入力をターミナルに接続してCommitizenを実行
  exec < /dev/tty
  # Commitizenを実行し、作成されたメッセージをコミットメッセージファイルに書き込む
  npx cz --hook || exit 1
fi
