/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123AccountsUserIdChar125RouteRouteImport } from './routes/{-$accountsUserId}/route'
import { Route as Char123AccountsUserIdChar125AccountLinksRouteImport } from './routes/{-$accountsUserId}/account-links'
import { Route as Char123AccountsUserIdChar125DeveloperRouteImport } from './routes/{-$accountsUserId}/developer'
import { Route as Char123AccountsUserIdChar125HelpRouteImport } from './routes/{-$accountsUserId}/help'
import { Route as Char123AccountsUserIdChar125LicensesRouteImport } from './routes/{-$accountsUserId}/licenses'
import { Route as Char123AccountsUserIdChar125PrivacyRouteImport } from './routes/{-$accountsUserId}/privacy'
import { Route as Char123AccountsUserIdChar125SettingsRouteImport } from './routes/{-$accountsUserId}/settings'
import { Route as Char123AccountsUserIdChar125TermsRouteImport } from './routes/{-$accountsUserId}/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123AccountsUserIdChar125RouteRoute =
  Char123AccountsUserIdChar125RouteRouteImport.update({
    id: '/{-$accountsUserId}',
    path: '/{-$accountsUserId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123AccountsUserIdChar125AccountLinksRoute =
  Char123AccountsUserIdChar125AccountLinksRouteImport.update({
    id: '/account-links',
    path: '/account-links',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125DeveloperRoute =
  Char123AccountsUserIdChar125DeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125HelpRoute =
  Char123AccountsUserIdChar125HelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125LicensesRoute =
  Char123AccountsUserIdChar125LicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125PrivacyRoute =
  Char123AccountsUserIdChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125SettingsRoute =
  Char123AccountsUserIdChar125SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)
const Char123AccountsUserIdChar125TermsRoute =
  Char123AccountsUserIdChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123AccountsUserIdChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$accountsUserId}': typeof Char123AccountsUserIdChar125RouteRouteWithChildren
  '/{-$accountsUserId}/account-links': typeof Char123AccountsUserIdChar125AccountLinksRoute
  '/{-$accountsUserId}/developer': typeof Char123AccountsUserIdChar125DeveloperRoute
  '/{-$accountsUserId}/help': typeof Char123AccountsUserIdChar125HelpRoute
  '/{-$accountsUserId}/licenses': typeof Char123AccountsUserIdChar125LicensesRoute
  '/{-$accountsUserId}/privacy': typeof Char123AccountsUserIdChar125PrivacyRoute
  '/{-$accountsUserId}/settings': typeof Char123AccountsUserIdChar125SettingsRoute
  '/{-$accountsUserId}/terms': typeof Char123AccountsUserIdChar125TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{-$accountsUserId}': typeof Char123AccountsUserIdChar125RouteRouteWithChildren
  '/{-$accountsUserId}/account-links': typeof Char123AccountsUserIdChar125AccountLinksRoute
  '/{-$accountsUserId}/developer': typeof Char123AccountsUserIdChar125DeveloperRoute
  '/{-$accountsUserId}/help': typeof Char123AccountsUserIdChar125HelpRoute
  '/{-$accountsUserId}/licenses': typeof Char123AccountsUserIdChar125LicensesRoute
  '/{-$accountsUserId}/privacy': typeof Char123AccountsUserIdChar125PrivacyRoute
  '/{-$accountsUserId}/settings': typeof Char123AccountsUserIdChar125SettingsRoute
  '/{-$accountsUserId}/terms': typeof Char123AccountsUserIdChar125TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$accountsUserId}': typeof Char123AccountsUserIdChar125RouteRouteWithChildren
  '/{-$accountsUserId}/account-links': typeof Char123AccountsUserIdChar125AccountLinksRoute
  '/{-$accountsUserId}/developer': typeof Char123AccountsUserIdChar125DeveloperRoute
  '/{-$accountsUserId}/help': typeof Char123AccountsUserIdChar125HelpRoute
  '/{-$accountsUserId}/licenses': typeof Char123AccountsUserIdChar125LicensesRoute
  '/{-$accountsUserId}/privacy': typeof Char123AccountsUserIdChar125PrivacyRoute
  '/{-$accountsUserId}/settings': typeof Char123AccountsUserIdChar125SettingsRoute
  '/{-$accountsUserId}/terms': typeof Char123AccountsUserIdChar125TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$accountsUserId}'
    | '/{-$accountsUserId}/account-links'
    | '/{-$accountsUserId}/developer'
    | '/{-$accountsUserId}/help'
    | '/{-$accountsUserId}/licenses'
    | '/{-$accountsUserId}/privacy'
    | '/{-$accountsUserId}/settings'
    | '/{-$accountsUserId}/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$accountsUserId}'
    | '/{-$accountsUserId}/account-links'
    | '/{-$accountsUserId}/developer'
    | '/{-$accountsUserId}/help'
    | '/{-$accountsUserId}/licenses'
    | '/{-$accountsUserId}/privacy'
    | '/{-$accountsUserId}/settings'
    | '/{-$accountsUserId}/terms'
  id:
    | '__root__'
    | '/'
    | '/{-$accountsUserId}'
    | '/{-$accountsUserId}/account-links'
    | '/{-$accountsUserId}/developer'
    | '/{-$accountsUserId}/help'
    | '/{-$accountsUserId}/licenses'
    | '/{-$accountsUserId}/privacy'
    | '/{-$accountsUserId}/settings'
    | '/{-$accountsUserId}/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123AccountsUserIdChar125RouteRoute: typeof Char123AccountsUserIdChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$accountsUserId}': {
      id: '/{-$accountsUserId}'
      path: '/{-$accountsUserId}'
      fullPath: '/{-$accountsUserId}'
      preLoaderRoute: typeof Char123AccountsUserIdChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$accountsUserId}/account-links': {
      id: '/{-$accountsUserId}/account-links'
      path: '/account-links'
      fullPath: '/{-$accountsUserId}/account-links'
      preLoaderRoute: typeof Char123AccountsUserIdChar125AccountLinksRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/developer': {
      id: '/{-$accountsUserId}/developer'
      path: '/developer'
      fullPath: '/{-$accountsUserId}/developer'
      preLoaderRoute: typeof Char123AccountsUserIdChar125DeveloperRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/help': {
      id: '/{-$accountsUserId}/help'
      path: '/help'
      fullPath: '/{-$accountsUserId}/help'
      preLoaderRoute: typeof Char123AccountsUserIdChar125HelpRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/licenses': {
      id: '/{-$accountsUserId}/licenses'
      path: '/licenses'
      fullPath: '/{-$accountsUserId}/licenses'
      preLoaderRoute: typeof Char123AccountsUserIdChar125LicensesRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/privacy': {
      id: '/{-$accountsUserId}/privacy'
      path: '/privacy'
      fullPath: '/{-$accountsUserId}/privacy'
      preLoaderRoute: typeof Char123AccountsUserIdChar125PrivacyRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/settings': {
      id: '/{-$accountsUserId}/settings'
      path: '/settings'
      fullPath: '/{-$accountsUserId}/settings'
      preLoaderRoute: typeof Char123AccountsUserIdChar125SettingsRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
    '/{-$accountsUserId}/terms': {
      id: '/{-$accountsUserId}/terms'
      path: '/terms'
      fullPath: '/{-$accountsUserId}/terms'
      preLoaderRoute: typeof Char123AccountsUserIdChar125TermsRouteImport
      parentRoute: typeof Char123AccountsUserIdChar125RouteRoute
    }
  }
}

interface Char123AccountsUserIdChar125RouteRouteChildren {
  Char123AccountsUserIdChar125AccountLinksRoute: typeof Char123AccountsUserIdChar125AccountLinksRoute
  Char123AccountsUserIdChar125DeveloperRoute: typeof Char123AccountsUserIdChar125DeveloperRoute
  Char123AccountsUserIdChar125HelpRoute: typeof Char123AccountsUserIdChar125HelpRoute
  Char123AccountsUserIdChar125LicensesRoute: typeof Char123AccountsUserIdChar125LicensesRoute
  Char123AccountsUserIdChar125PrivacyRoute: typeof Char123AccountsUserIdChar125PrivacyRoute
  Char123AccountsUserIdChar125SettingsRoute: typeof Char123AccountsUserIdChar125SettingsRoute
  Char123AccountsUserIdChar125TermsRoute: typeof Char123AccountsUserIdChar125TermsRoute
}

const Char123AccountsUserIdChar125RouteRouteChildren: Char123AccountsUserIdChar125RouteRouteChildren =
  {
    Char123AccountsUserIdChar125AccountLinksRoute:
      Char123AccountsUserIdChar125AccountLinksRoute,
    Char123AccountsUserIdChar125DeveloperRoute:
      Char123AccountsUserIdChar125DeveloperRoute,
    Char123AccountsUserIdChar125HelpRoute:
      Char123AccountsUserIdChar125HelpRoute,
    Char123AccountsUserIdChar125LicensesRoute:
      Char123AccountsUserIdChar125LicensesRoute,
    Char123AccountsUserIdChar125PrivacyRoute:
      Char123AccountsUserIdChar125PrivacyRoute,
    Char123AccountsUserIdChar125SettingsRoute:
      Char123AccountsUserIdChar125SettingsRoute,
    Char123AccountsUserIdChar125TermsRoute:
      Char123AccountsUserIdChar125TermsRoute,
  }

const Char123AccountsUserIdChar125RouteRouteWithChildren =
  Char123AccountsUserIdChar125RouteRoute._addFileChildren(
    Char123AccountsUserIdChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123AccountsUserIdChar125RouteRoute:
    Char123AccountsUserIdChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
